name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches: [main] # Or whatever your main branch is

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (submodules)

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest" # Or your preferred Hugo version

      - name: Build Hugo Site
        run: hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # The folder Hugo outputs to
